### ISSUE TITLE
Create a standalone working example

### ISSUE THREAD

**Issue by leewisestamp** [frapontillo/angular-bootstrap-switch#105]
I was hoping that the example folder would work "out of the box" upon downloading it. It appears there are Bower and/or NPM dependencies and I don't use either of those frameworks. Would it be possible to create a "standalone" example for those of us still in the dark ages? Thanks!

**Comment by frapontillo** [comment]
There is [this plunker](http://plnkr.co/edit/SWy8YmrVi8IsTa4FuqSZ?p=preview) mentioned in CONTRIBUTING.
