### ISSUE TITLE
switch-on-text size bug of show not-english text 

### ISSUE THREAD

**Issue by yuanjingxp** [frapontillo/angular-bootstrap-switch#106]
> &lt;input bs-switch type="checkbox" ng-model="true" class="make-switch" data-on-text="@L("On")" data-off-text="@L("Off")" data-size="small"/&gt;
> &lt;input bs-switch type="checkbox" ng-model="true" class="make-switch" switch-on-text="@L("On")" switch-off-text="@L("Off")" switch-size="small"/&gt;

![qq 20160323113225](https://cloud.githubusercontent.com/assets/13447106/13974936/5b360082-f0eb-11e5-8e97-ad7c3c22380e.png)

**Comment by frapontillo** [comment]
What's the issue here?
