### ISSUE TITLE
no ng-change fired when change from undefined/null to false

### ISSUE THREAD

**Issue by martinschuberts** [frapontillo/angular-bootstrap-switch#107]
is there a chance to fire the ng-change when changing from undefined or null to false?
see here - changing for undefind to false will not show a console msg.
http://plnkr.co/edit/4lKEH5eE4kQRGQt9GEKy?p=info

used version 0.5.0 master

**Comment by frapontillo** [comment]
I think this can be included in the `switch-change` behavior if @icholy would like to take care of it :grin:.
We could add some checks at https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/src/directives/bsSwitch.js#L180.

**Comment by icholy** [comment]
I'll check it out

**Comment by icholy** [comment]
I'm thinking this is actually an issue with the way bootstrap switch works.

**Comment by icholy** [comment]
Here's the related issue: https://github.com/nostalgiaz/bootstrap-switch/issues/541

**Comment by martinschuberts** [comment]
there is also this pull request - having the same problem: [nostalgiaz/bootstrap-switch/pull/449](https://github.com/nostalgiaz/bootstrap-switch/pull/449)
Do I understand right that this has never made it's way to the release? Why not - any idea how to trigger them?
(I tried this and it works for me)

@frapontillo and @icholy what do you recommend me - I am quite new in this world...

**Comment by icholy** [comment]
@martinschuberts looks like the project isn't really maintained anymore. I'm still looking into it.

**Comment by icholy** [comment]
Ok, I got it. The `ngModelController.$formatters` and `ngModelController.$parsers` are messing with the values. so its not property detecting changes between `false` and `undefined`

**Comment by icholy** [comment]
I'm an idiot, I didn't realize you were trying to use `ngChange` instead of `switchChange`. Anyway, I've updated my PR to fix both issues.
