### ISSUE TITLE
switch-change should only fire if the switch itself changed the value

### ISSUE THREAD

**Issue by Deklin** [frapontillo/angular-bootstrap-switch#110]
Right now it fires if ANYONE changes the value.

**Comment by Deklin** [comment]
Also for reference, this is now ng-change works, only fires if the control/directive itself changed the value.

**Comment by frapontillo** [comment]
You should have read the contributing guidelines before opening an issue.

**Comment by Deklin** [comment]
Sure i'll take a look, however it doesn't detract from this being an issue. But let me research what you suggested and get back.
