### ISSUE TITLE
switch-change should only fire if the switch itself changed the value

### ISSUE THREAD

**Issue by Deklin** [frapontillo/angular-bootstrap-switch#111]
Here is a plunkr showing the issue.
http://plnkr.co/edit/NYLyEUBz2fs3XFCKtCjS?p=preview

Basically lets compare ng-change to switch-change

ng-change only fires if the directive/controller managing the model makes the change, an outside change will not fire this

switch-change will fire if the model is changed even outside the angular-bootstrap-switch codebase.

**Comment by Deklin** [comment]
In the plunkr you can compare the behavior between the checkbox and the switch itself.

**Comment by frapontillo** [comment]
According to the documentation, "`switch-change` evaluates an expression when the model value changes". I am not going to handle out-of-Angular events in an Angular directive.
`ng-change` will instead fire when the view value changes, according to the AngularJS spec. 

You may want to read the discussion [here](https://github.com/frapontillo/angular-bootstrap-switch/pull/109).

**Comment by Deklin** [comment]
I can't believe I missed the fact that ng-change works on this... !! For some reason I read switch-change as your implementation of ng-change and that I was to use that instead of ng-change.
Just tested ng-change on the plunkr and it works fine.

Thanks for your quick reply and feedback.

**Comment by tucq88** [comment]
Yeah, I was like @Deklin . I thought that ng-change & switch-change doing same thing. How stupid. 
Maybe we should update this into the README so people might not misunderstand this anymore.

**Comment by frapontillo** [comment]
@tucq88 I will gladly accept PRs.
