### ISSUE TITLE
Can not set switch-on-text and switch-off-text to empty string

### ISSUE THREAD

**Issue by dmitry-kostin** [frapontillo/angular-bootstrap-switch#112]
Hello,
Tried to set empty string to switch values
false, null, '', undefined, {{''}}, and etc. do now work, any help?

**Comment by frapontillo** [comment]
If you want to use an empty string, you can try to use `&nbsp;`. Please tell me if this works out for you.

**Comment by dmitry-kostin** [comment]
Hi thanks for quick response,
No unfortunately this not worked
Created a pull request for this

**Comment by frapontillo** [comment]
Can you share a plunker to test the behavior?

**Comment by dmitry-kostin** [comment]
https://plnkr.co/edit/ffGptPSHkztfgJnhnW26?p=preview

**Comment by frapontillo** [comment]
It looks like Angular reads the initial `attr="&nbsp;"` as the empty string, and therefore the plugin defaults to `'ON'` and `'OFF'`.
A workaround would be to use an explicit expression such as `switchOnText="{{'&nbsp;'}}"` (see working demo here: https://plnkr.co/edit/bxe6Hn?p=preview
