### ISSUE TITLE
triggering switchChange on model change breaks my app

### ISSUE THREAD

**Issue by mkrauser** [frapontillo/angular-bootstrap-switch#116]
The change in 8c9db85c2b6c6a7363aaa413f29013b2b6d2c372 is causing problem in my application. We load the data with ajax request and bind it to the switches. Since that change the binding triggers a switch-change and in our case, this breaks the app.

Is there any chance to make this behaviour optional?

**Comment by frapontillo** [comment]
If you want to bind only to view changes, you can use `ng-change`.

**Comment by mkrauser** [comment]
Ah, sometimes you just don't see the obvious. Thank you very much for the quick response and your work on this!
