### ISSUE TITLE
Rendering issue with bootstrap-switch

### ISSUE THREAD

**Issue by fishycrakers** [frapontillo/angular-bootstrap-switch#117]
I'll leave an image below.

When loading the bs-switch directive, onto an input element, the switch is
rendered with tabs in this order ["Yes","No","blank"],
whereas they should be rendered thusly ["Yes", "blank", "No"].

Could you advise on what might be causing this issue?

![basswitch](https://cloud.githubusercontent.com/assets/18060385/17249631/bf4f62fe-5598-11e6-8c58-49cd67bf30d5.png)

**Comment by frapontillo** [comment]
There must be some other CSS conflicting.
If you need help please read the notice on how to contribute.
