### ISSUE TITLE
can not pass event as parameter to switch-change event

### ISSUE THREAD

**Issue by kranthi2016** [frapontillo/angular-bootstrap-switch#118]
This is my controller code
    $scope.onFreezeChange = function (e) {
        e.preventDefault();  // have to prevent default for certain conditions
    
    }

... and html contains below

input bs-switch ng-model="column.IsFreeze" type="checkbox" switch-size="mini"  switch-on-text="Freeze" switch-off-text="UnFreeze"   switch-change="onFreezeChange($event)" 

On change event got fired but unable to pass event as parameter to controller function.
i appreciate any suggestions

**Comment by frapontillo** [comment]
There's no event bound to `switch-change`, i.e. what you're asking is not possible.
