### ISSUE TITLE
Support for angular 1.6

### ISSUE THREAD

**Issue by Sheeryada** [frapontillo/angular-bootstrap-switch#123]
Hi, Does this support angular 1.6.x versions?

**Comment by frapontillo** [comment]
I have no idea, I am not actively maintaining this project anymore.

**Comment by ygilliot** [comment]
I use it with angular 1.6.2. No problem until now.

**Comment by frapontillo** [comment]
Can you please follow the [**very detailed instructions**](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/CONTRIBUTING.md) on how to report an issue?
