### ISSUE TITLE
confirmation for toggle switch

### ISSUE THREAD

**Issue by smohammedyasin** [frapontillo/angular-bootstrap-switch#124]
Hi,

How can i show confirmation popup before set "ON" Or "OFF".
i have found very good script in jquery bootstrap. [https://jsfiddle.net/hL0as0mv/122/](https://jsfiddle.net/hL0as0mv/122/) .
could any one help me get same way in angluar switch.

Appreciate for Best & Quick response

**Comment by frapontillo** [comment]
You can use `switch-change` to do whatever you want and eventually revert to the inverse value if the confirmation is not successful.

Please re-open the issue if you still have this problem.

**Comment by vidyashreejy** [comment]
Please explain how to use switch-change to pop up a confirmation modal before toggling the switch. I'm new to angular so please help me. thanks in advance
