### ISSUE TITLE
Does not initialize in Angular 1.5.11 project

### ISSUE THREAD

**Issue by smlombardi** [frapontillo/angular-bootstrap-switch#126]
Throws a console error:

`Error: d.bootstrapSwitch is not a function. (In 'd.bootstrapSwitch', 'd.bootstrapSwitch' is undefined)`

![screen shot 2017-03-22 at 8 59 25 am](https://cloud.githubusercontent.com/assets/835148/24198833/e0f972f6-0edd-11e7-9353-a1c60a7fe41a.png)

I links the min.js file from dist folder, injected the module and added this to my page:

```
<input bs-switch type="checkbox"
                     ng-model="switch.isSelected"
                     ng-true-value="'yep'"
                     ng-false-value="'nope'">
```
where the controller is "controller as switch".  In the controller I only have 
`_this.isSelected = true;`

**Comment by frapontillo** [comment]
Please read this: https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/CONTRIBUTING.md#-report-an-issue
