### ISSUE TITLE
Switch controlling / disabling another switch

### ISSUE THREAD

**Issue by chasingtheflow** [frapontillo/angular-bootstrap-switch#127]
Hi,

I have an issue where I have two switches, one which controls both the state and read-only attribute of the second switch. 

Essentially it's the following:

```HTML
<label for="active-switch">Active</label>
<input id="active-switch" type="checkbox" bs-switch="" ng-model="vm.active" switch-change="vm.toggleActive()"/>
<label for="info-switch">Info</label>
<input id="info-switch" type="checkbox" bs-switch="" ng-model="vm.showInfo" switch-active="{{vm.active}}"/>		
```
```javascript
vm.toggleActive = function() {
    vm.showInfo = vm.toggleActive;
}
```

So when the Active switch is turned off then the Info Switch should turn off and be disabled. When the active switch turns back on the Info Switch should turn back on and no longer be disabled. 

Instead the Info switch is disabled but it's state does not  update. If I take off the switch-active attribute then the first switch correctly toggles the second switch.

Is there a better way to achieve this?

Thanks!

**Comment by frapontillo** [comment]
Please read this: https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/CONTRIBUTING.md#-report-an-issue

**Comment by chasingtheflow** [comment]
Here is a demo: http://plnkr.co/edit/pvsMEDWNI5t87XeeHSoh?p=preview

**Comment by chasingtheflow** [comment]
Do I need to reopen a new issue now that I have provided a demo?

**Comment by frapontillo** [comment]
@chasingtheflow no, it's ok 😄 I'll take a look as soon as I have a moment. Thanks.

**Comment by chasingtheflow** [comment]
Okay! No problem. I have a work around / hack that's working for me for the time being anyhow. Thanks

**Comment by chasingtheflow** [comment]
Any progress on this?
