### ISSUE TITLE
Does not respect ngTrueValue/ngFalseValue

### ISSUE THREAD

**Issue by jeffsrepoaccount** [frapontillo/angular-bootstrap-switch#24]
I have the following checkbox, that works correctly when I dump the object out into the view with `{{ component | json }}`:

``` HTML
<input type="checkbox" 
    data-ng-model="component.contains" 
    ng-true-value="1" ng-false-value="0"/>
```

However, adding the `bs-switch` directive causes the model to get 'stuck' in the on position:

``` HTML
<input type="checkbox" 
    bs-switch
    data-ng-model="component.contains" 
    ng-true-value="1" ng-false-value="0"/>
```

The switch moves back and forth, but the underlying model is not updated, rather it stays at `"1"`

Is there a workaround where you can use 1/0 instead of true/false?

**Comment by josuesamano** [comment]
Don't show correctly in chrome this control

![angswitch](https://cloud.githubusercontent.com/assets/5949714/11520061/2bba742a-9865-11e5-8416-2ca749497b3f.PNG)

**Comment by frapontillo** [comment]
@josuesamano please open a separate issue following the [contributing guidelines](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/CONTRIBUTING.md). Thanks.
