### ISSUE TITLE
First toggle do not change ngModel value 

### ISSUE THREAD

**Issue by kfiil** [frapontillo/angular-bootstrap-switch#37]
Hey,

Greate direcitve:) I have a small issue, the first toggle do not change the value of ngModel, if I call 

```
controller.$setViewValue(controller.$modelValue); 
```

just after

```
element.bootstrapSwitch('state', controller.$modelValue || false, true); (line 121)
```

it works, do that make sense?

-KFIIL

**Comment by mitsos1os** [comment]
Hi! Very cool module!
I wanted to note that I also face the same issue but under this circumstances. I open a modal with the use of angular-ui directives and pass some variables by using the resolve property in the modal configuration object. If I bind this to switch, then yes it still requires a first toggle on and off to start affecting ng-model value. However if i bind the switch to a local variable in the template, then the switch works immediately.

**Comment by raygerrard** [comment]
Any chance we can get this fix pushed to bower?

**Comment by frapontillo** [comment]
I am yet to solve more open issues since the rewrite in `0.4.0`. I will release it as soon as possible.
