### ISSUE TITLE
error when setting the value of ng-model to "true" manually

### ISSUE THREAD

**Issue by joeltello** [frapontillo/angular-bootstrap-switch#43]
If I set the variable to true in my controller, the first 2 times I click on the switch it doesn't update the ng-model variable.

check out this plunker 

http://plnkr.co/edit/fHZficmknopo2hGhsLh4?p=preview

**Comment by helenitvn** [comment]
Hi,
Did this issue fixed in v0.3.0. I still have the same problem...

**Comment by frapontillo** [comment]
The issue was fixed in `0.4.0-alpha.1`.
