### ISSUE TITLE
Radio button sample

### ISSUE THREAD

**Issue by softengi** [frapontillo/angular-bootstrap-switch#46]
Could you provide any sample code for radio button implementation (plunkr or something)? I am having a hard time to make this work with radio buttons and could not find a sample code anywhere.

**Comment by frapontillo** [comment]
As of 210b5c0, the radio option is properly supported.
You need to:

* set the same `ng-model` and `name` attributes to all of the radios
* set different `ng-value` or `value` attributes to all of the radios

Example:

```html
  <input bs-switch
    ng-model="result"
    type="radio"
    ng-value="'one'">

  <input bs-switch
    ng-model="result"
    type="radio"
    ng-value="'two'">

  {{ result }}
```

`$scope.result` will equal to `'one'` or `'two'`; if you also set the `switch-radio-off` attribute to `true`, unselecting a radio will cause `result` to become `undefined`.
