### ISSUE TITLE
Is it possible to add an ng-click event to the switch?

### ISSUE THREAD

**Issue by nofear87** [frapontillo/angular-bootstrap-switch#53]
depending on the id the switch gives to a function I will change something. So I have to watch multiple switches and react on there ids? Is it possible to add a ng-click="doSomething(id1)"? Or is there a better way doing this? Thank you!

**Comment by forcewill** [comment]
Yes but im using it on a table like

```html
<tr data-ng-repeat="user in displayed">
...
 <input
                        bs-switch
                        type="checkbox"
                        data-ng-click="toggleUserActive(user)"
                        ng-model="user.active"
                        switch-on-text="{{ 'Active' || i18n }}"
                        switch-off-text="{{ 'Disabled' || i18n }}"
                        switch-on-color="success"
                        switch-off-color="danger"
                        switch-size="mini">
```

for this use case ```$watch``` doesn't seem to fit in or should i use watch in this case ? 
and if so how would i do it one per user ? Seems overhead.

**Comment by frapontillo** [comment]
You should use `$watch`, `ng-click` is not the right approach to your problem.

**Comment by Cdvalencia** [comment]
Hola!

Aquí está la solución: http://stackoverflow.com/questions/13077320/angularjs-trigger-when-radio-button-is-selected

**Comment by Deklin** [comment]
I would say there is a different issue here

switch-change is firing on anyone changing the model object. I would expect switch-change to fire if IT changed the model object. Having that, then no need for ng-click.
