### ISSUE TITLE
Trigger digest cycle in bootstrap-switch event handler

### ISSUE THREAD

**Issue by queezythegreat** [frapontillo/angular-bootstrap-switch#54]
Hi,

The event handler which updates the the ng-model does not trigger the angular digest cycle, which causes the model to not be updated immediately. The code in question is [src/directives/bsSwitch.js#L199](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/src/directives/bsSwitch.js#L199).

You should add the following to make the changes immediate:
```
scope.$apply();
```

Here are some links about $apply:

http://jimhoskins.com/2012/12/17/angularjs-and-apply.html
https://docs.angularjs.org/api/ng/type/$rootScope.Scope

Sorry about no giving you a pull request, did not have any time to fork your project on GitHub.

Anyways thanks for the great angular extension for bootstrap-switch.

**Comment by rafaelmotta** [comment]
+1

**Comment by frapontillo** [comment]
Could you please add a live demo?

**Comment by kaelite** [comment]
in angular-bootstrap-switch.js in row 186 changing
controller.$setViewValue(data);  -->  scope.$apply(function(){controller.$setViewValue(data);});
resolved the issue for me.
thanx for a nice widget!

**Comment by chrism-dp** [comment]
this worked for me also. 

incidentally, versions 0.3.0-alpha.1 & 2 were both wrapped this way

**Comment by frapontillo** [comment]
No demo provided, please feel free to reopen it if you have a simple demo that demonstrates the issue.
