### ISSUE TITLE
Error message when adding module

### ISSUE THREAD

**Issue by dlwhiteman** [frapontillo/angular-bootstrap-switch#55]
Here how I am adding the module to my app:

var theApp = angular.module("theApp", ["sizeFilter", "frameRateFilter", "bitRateFilter", "angularBootstrapNavTree", "ngAnimate", "nvd3", "mgcrea.ngStrap.select", "frapontillo.bootstrap-switch"
]);

When I add this module to my app, I immediately get the following error in my console.  I'm assuming there is a possible incompatibility between angular-bootstrap-switch and one of the other modules or libs that I have installed.

http://localhost:9000/admin/webjars/jquery/2.1.1/jquery.min.js is being assigned a //# sourceMappingURL, but already has one
http://localhost:9000/admin/webjars/angularjs/1.3.6/angular.min.js is being assigned a //# sourceMappingURL, but already has one
http://localhost:9000/admin/webjars/angularjs/1.3.6/angular-animate.min.js is being assigned a //# sourceMappingURL, but already has one
http://localhost:9000/admin/webjars/angular-strap/2.1.4/angular-strap.min.js is being assigned a //# sourceMappingURL, but already has one
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.js:486
Error: [$injector:modulerr] http://errors.angularjs.org/1.3.6/$injector/modulerr?p0=theApp&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.6%2F%24injector%2Fmodulerr%3Fp0%3Dfrapontillo.bootstrap-switch%26p1%3D%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.3.6%252F%2524injector%252Fnomod%253Fp0%253Dfrapontillo.bootstrap-switch%250AA%252F%253C%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A6%253A409%250AMd%252F%253C%252F%253C%252F%253C%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A21%253A328%250Aa%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A20%253A464%250AMd%252F%253C%252F%253C%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A21%253A211%250Ag%252F%253C%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A35%253A273%250Ar%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A7%253A288%250Ag%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A35%253A123%250Ag%252F%253C%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A35%253A281%250Ar%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A7%253A288%250Ag%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A35%253A123%250AOb%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A38%253A358%250Asc%252Fd%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A17%253A348%250Asc%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A18%253A146%250AHd%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A16%253A490%250A%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fangularjs%252F1.3.6%252Fangular.min.js%253A249%253A238%250An.Callbacks%252Fj%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fjquery%252F2.1.1%252Fjquery.min.js%253A2%253A26852%250An.Callbacks%252Fk.fireWith%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fjquery%252F2.1.1%252Fjquery.min.js%253A2%253A27661%250A.ready%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fjquery%252F2.1.1%252Fjquery.min.js%253A2%253A29482%250AI%2540http%253A%252F%252Flocalhost%253A9000%252Fadmin%252Fwebjars%252Fjquery%252F2.1.1%252Fjquery.min.js%253A2%253A29656%250A%0AA%2F%3C%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A6%3A409%0Ag%2F%3C%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A36%3A28%0Ar%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A7%3A288%0Ag%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A35%3A123%0Ag%2F%3C%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A35%3A281%0Ar%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A7%3A288%0Ag%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A35%3A123%0AOb%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A38%3A358%0Asc%2Fd%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A17%3A348%0Asc%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A18%3A146%0AHd%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A16%3A490%0A%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fangularjs%2F1.3.6%2Fangular.min.js%3A249%3A238%0An.Callbacks%2Fj%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fjquery%2F2.1.1%2Fjquery.min.js%3A2%3A26852%0An.Callbacks%2Fk.fireWith%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fjquery%2F2.1.1%2Fjquery.min.js%3A2%3A27661%0A.ready%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fjquery%2F2.1.1%2Fjquery.min.js%3A2%3A29482%0AI%40http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fwebjars%2Fjquery%2F2.1.1%2Fjquery.min.js%3A2%3A29656%0A angular.min.js:6

**Comment by frapontillo** [comment]
It seems like you didn't reference the directive file at all.
Can't reproduce, please attach a working plunker.
