### ISSUE TITLE
Some attributes does not working

### ISSUE THREAD

**Issue by davidsmith242** [frapontillo/angular-bootstrap-switch#59]
I'm trying to use your directive as part of a template within an another directive. Some of attributes gets ignored: switch-readonly, switch-label-width, switch-handle-width. Also the value of ng-true-value and ng-false-value are not working correctly. I added a watch for the ng-model value, but the replied value after toggle is always '' (empty string)

"angular": "~1.2.26",
"jquery": "~2.1.0",
"bootstrap": "~3.2.0",
"bootstrap-switch":"3.0.2",
"angular-bootstrap-switch": "~0.3.0"

**Comment by frapontillo** [comment]
I need a demo on plnkr in order to help you.

**Comment by davidsmith242** [comment]
http://plnkr.co/edit/X2ESAJqwJ7TFNRCnlAhg
In the plunker switch-label-width, switch-handle-width are working fine, but switch-readonly doesn't.

**Comment by frapontillo** [comment]
I'm pretty sure you did something wrong with your directive. `readonly` is a [well tested feature](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/test/spec/directives/bsSwitchSpec.js#L301-L302).
