### ISSUE TITLE
Indeterminate first click always defaults to Yes / True

### ISSUE THREAD

**Issue by Sheparzo** [frapontillo/angular-bootstrap-switch#60]
Right now, the indeterminate state always goes to yes upon first click and must be clicked a second time to go to no.

The indeterminate state should be smart enough to switch to a yes or no upon first click depending on where the user clicks the switch.  The current indeterminate example on http://www.bootstrap-switch.org/examples.html is smart enough to work this way.

**Comment by frapontillo** [comment]
Could you please provide a demo?

**Comment by frapontillo** [comment]
I may be terribly wrong, but it seems to me that the demo version of the original `bootstrap-switch` behaves exactly as the angular directive. If I click on an indeterminate switch it always sets itself to `true`.
