### ISSUE TITLE
First toggle do not change ngModel value (UPDATED)

### ISSUE THREAD

**Issue by mitsos1os** [frapontillo/angular-bootstrap-switch#61]
Hi, I have also commented on the previous similar iissue but since it was closed I do not know if it is monitored... 
So there is a problem when multiple bs-switches exist...
I found out that the problem is when you try to bind ng-model to an existing property of an object inside an array. If it is **not  the first element of the array** and the property exists, it needs the first toggle cycle for binding to start working. If it **is the first element** it works no matter what directly

**Comment by mkaluzny** [comment]
+1

**Comment by mitsos1os** [comment]
Yes you are right! It is resolved on latest version.
