### ISSUE TITLE
element.bootstrapSwitch undefined

### ISSUE THREAD

**Issue by daw451-duplicate** [frapontillo/angular-bootstrap-switch#64]
when i wire up and run with the angular version i get an error stating that the bootstrapSwitch is undefined.

i was trying to test to see if ng-true-value="0" and ng-false-value="1" work with this control. Seems to work with the jquery version but of course then i would need a directive to  talk with the model. Prefer to go this route.

aaron

**Comment by frapontillo** [comment]
Check out all the scripts included in the [example](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/example/index.html) page. What's different? What's missing'

**Comment by frankvictor** [comment]
I encountered the same problem and finally found out why:
the js file include order matters:
```
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<script src="bower_components/angular/angular.min.js"></script>
```
jquery.min.js must be included before angular.min.js.

Reason:
> elem – The jQLite (a subset of jQuery) wrapped element on which the directive is applied. If you have included jQuery in the HTML before AngularJS is included, this becomes jQuery wrapped instead of jQLite. As the element is already wrapped with jQuery/jQLite, there is no need to again wrap it inside $() for DOM manipulations.
- http://www.sitepoint.com/practical-guide-angularjs-directives/
