### ISSUE TITLE
ngModel updates after 3 switches

### ISSUE THREAD

**Issue by silintzir** [frapontillo/angular-bootstrap-switch#65]
when the ngModel is initially true and the checkbox is "on", the first time i uncheck it the ngModel does not update but stays true. I have to recheck it and then re-uncheck it to update the ngModel.

**Comment by timcullen** [comment]
I have the same problem.  How did you fix it?

**Comment by mastermind1981** [comment]
I have the same problem, is there any solution?

**Comment by mastermind1981** [comment]
Could you please re open the issue?

**Comment by frapontillo** [comment]
@mastermind1981 I need a live demo at the very least, please open a new issue after reading the [CONTRIBUTING](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/CONTRIBUTING.md) guidelines.

**Comment by mastermind1981** [comment]
ok, I updated to the new version and it seems working.

**Comment by frapontillo** [comment]
Good to know :+1:
