### ISSUE TITLE
use IIFE to wrap 'use strict'

### ISSUE THREAD

**Issue by amirgalor** [frapontillo/angular-bootstrap-switch#66]
putting 'use strict' globally forces the strict mode on entire application.

It's better to wrap in IIFE, adding 'use strict' in inner scope.

**Comment by frapontillo** [comment]
Fair enough.
For my future reference, [this](https://github.com/angular/angular.js/blob/master/src/angular.prefix) is how the Angular team does that.

**Comment by amirgalor** [comment]
Yup - that's the even-better-version :)

**Comment by frapontillo** [comment]
Fixed by 0bddd03d9fb62744f946daa9f5cd70003d9da30e
