### ISSUE TITLE
ng-init="checked=true" is ignored

### ISSUE THREAD

**Issue by romant** [frapontillo/angular-bootstrap-switch#69]
looks to always render `false` by default

current definition is:

```js
input(
  bs-switch
  type="checkbox"
  ng-init="checked=true"
  ng-model="selectionCriteria.mode"
  ng-change="selectionCriteriaToggle()"
  switch-on-text="Simple"
  switch-off-text="Advanced"
  switch-on-color="success"
  switch-off-color="info"
  switch-size="70")
```

**Comment by frapontillo** [comment]
What is 'checked'? You are binding to selectionCriteria.mode, not to checked.

**Comment by romant** [comment]
Hi @frapontillo - thanks for the prompt feedback.

Am looking to make the default of the checkbox / angular-bootstrap-switch to be `true` / checked.

If I understood the behaviour correctly, the `ng-init="checked=true"` is the equivalent of html's `checked` - yet this is being ignored it seems.

Hence the raising of the issue.

**Comment by frapontillo** [comment]
No, `ng-init` is for calling some code when the view is compiled. With that code you're simply setting a `$scope.checked` variable to `true`, then you never use `$scope.checked` again.

**Comment by romant** [comment]
I see. My only goal is to have the checkbox set to true on page render. Equivalent behaviour of <input checked…/> . Yet with angular-boot-strap-switch am unable to see a way to do it. Any hints? Thank you.

**Comment by frapontillo** [comment]
You have to set `selectionCriteria.mode` to `true` in your controller. `ngInit` [is to be used](https://docs.angularjs.org/api/ng/directive/ngInit) for initialization with `ngRepeat` only.

**Comment by romant** [comment]
Thanks for the details. Am new to Angular - so appreciate it the details.

What happens with the control though is this: if I have `ng-model` set in the view, upon toggle, the model gets updated. Namely set to true or false.

If on the other hand am setting the same model to a default action in the controller as you suggest, although the UI is affected on render; the model doesn't get updated on toggle until the 3rd time.

Have tried this now a few times, and always the same behaviour. Basically angular-bootstrap-switch doesn't update the model upon initial toggle / click - IF it has already been initialised in the controller.

**Comment by frapontillo** [comment]
I **really** need a live demo to help you with that.

**Comment by romant** [comment]
Looks like an angular version issue.

Please see [here](https://github.com/romant/bootstrap-angular-bug)

Anything above the 1.2.x ends up in the above behaviour.

**Comment by frapontillo** [comment]
@romant excellent, have you tried using `0.4.0-alpha.2`? Can you confirm me the solves the issue? If that is the case, I'll finally make a stable release.

**Comment by romant** [comment]
confirmed

`angular-bootstrap-switch#0.4.0-alpha.2` works like a charm.

**Comment by frapontillo** [comment]
:+1: appreciate it
