### ISSUE TITLE
Dist files are missing property bindings 'switchInverse' and 'switchReadonly'

### ISSUE THREAD

**Issue by andrewmtoy** [frapontillo/angular-bootstrap-switch#70]
The dist files are missing two property bindings: 'switchInverse' and 'switchReadonly'.
Perhaps the dist files aren't up to date? 

Dist file bindings:
https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/dist/angular-bootstrap-switch.js#L153

Src directive bindings: 
https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/src/directives/bsSwitch.js#L172

**Comment by frapontillo** [comment]
Yes, those features were added after `0.4.0-alpha.1`, I am going to prepare an `alpha.2` release that will include both `switch-inverse` and `switch-readonly`.

**Comment by frapontillo** [comment]
Closed by a60c5688f3de5794cb4e40dfa4934f5efe50066c.
