### ISSUE TITLE
Switch does not update AngularJS Model

### ISSUE THREAD

**Issue by Kostronor** [frapontillo/angular-bootstrap-switch#71]
I have prepared a Plnkr for you: http://plnkr.co/edit/LeL3kgnO4fKYqOQW9HFk?p=preview

clicking the switch does not update ng-show/ng-hide

Is there a work around?

Regards

**Comment by frapontillo** [comment]
Using the latest version of AngularJS (1.3.15) solves it.

```html
 <script src="https://code.angularjs.org/1.3.15/angular.js"></script>
```

**Comment by Kostronor** [comment]
Thanks a lot! Working perfectly!
