### ISSUE TITLE
Not properly honouring ngTrueValue

### ISSUE THREAD

**Issue by nathanmarks** [frapontillo/angular-bootstrap-switch#73]
When you have something like this:

```js
ng-true-value="{{ 1 | json }}"
```

It is not properly honoured due to this:
```js
if (!angular.isString(trueValue)) {
  trueValue = true;
}
```

It changes your true value from `1` to `true`. It breaks the switch and actually changes the model to the ngFalseValue when the switch is initialized. The checkboxes work perfectly with the `bs-switch` directive removed.

**Comment by bobmulder** [comment]
Why is this not merged? ng-true-value isn't working for me :$

**Comment by frapontillo** [comment]
It was merged into a release. If it's not working for you, please open a new issue with a live demo of what's going on.

Thank you.
