### ISSUE TITLE
Uncaught Error: [$injector:nomod] Module 'frapontillo.bootstrap-switch' is not available! 

### ISSUE THREAD

**Issue by hdramos** [frapontillo/angular-bootstrap-switch#74]
I am very new to anguarjs. I am using the latest versions of all libraries involved. When load my page I get the following error:

Uncaught Error: [$injector:nomod] Module 'frapontillo.bootstrap-switch' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I can get rid of this error by changing this line in the bsSwitch.js file:

angular.module('frapontillo.bootstrap-switch')

to

angular.module('frapontillo.bootstrap-switch',[])

With this change everything works fine. My feeling is that it has to do with the version of angular I am using.  Whats going on?

angular: 1.3.10
bootstrap: 3.3.4
bootstrap-switch: 3.3.2

**Comment by frapontillo** [comment]
I think you referenced the file under `src`: don't do that, just inclulde what's in the `dist` folder only.

**Comment by melino** [comment]
I trapped into that, too.
The example uses ../src/directives/bsSwitch.js, which is confusing, I think.

**Comment by frapontillo** [comment]
@melino the example references the common file as well. Also, the example is to visually test stuff while developing.

**Comment by melino** [comment]
Makes sense. :-)
