### ISSUE TITLE
ng-model attribute not working in tabset tag

### ISSUE THREAD

**Issue by lizhong8532** [frapontillo/angular-bootstrap-switch#75]
I in ui.bootstrap's tabset tag using angular-bootstrap-switch, like this:
```<input bs-switch ng-model="isSelected" type="checkbox" />```
But when toggle this switch then watch $scope.isSelected  no any change, 
I try move the input tag to tabset tag outside then the swtch can working

Is this bug?

**Comment by frapontillo** [comment]
Dupe #52
