### ISSUE TITLE
on/off callback function?

### ISSUE THREAD

**Issue by akocmark** [frapontillo/angular-bootstrap-switch#77]
how can i call a function on bootstrap-switch-change ? I know i can use ng-change, but how can I stop the switch if a certain condition fails? i tried returning false value but no luck. Thanks!

**Comment by frapontillo** [comment]
Sorry, that's out of the scope of this module. You can set up a watcher on your model that reverts `newValue` back to `oldValue` if the validation doesn't meet your criteria. Alternatively, you may want to bind the switch to a checked model that is only changed by you when a second model is changed by the user.

**Comment by akocmark** [comment]
If you try to set up watcher on the model that reverts newValue back to oldValue, you'll get an infinite digest loop, because the criteria always fails. I will try with the duplicated hidden checkbox tho. Thank you for the quick reply.

**Comment by frapontillo** [comment]
You could even try another approach: since you know when the user can toggle the switch, you may want to deactivate it when a user toggle would make it enter in a "non valid" state.
