### ISSUE TITLE
bower:~1.4.0 - better >=1.3.0

### ISSUE THREAD

**Issue by piernik** [frapontillo/angular-bootstrap-switch#78]
Now I cannot update using angular 1.3
I suppose it's still compatibile with angular 1.3 so better use >=1.3.0

**Comment by frapontillo** [comment]
You can still use angular-1.3.x, simply put it in your dependencies and/or resolutions.
Since angular-1.4 has breaking changes from 1.3 I can't test nor guarantee that angular-bootstrap-switch will work with 1.3.

**Comment by piernik** [comment]
it works with 1.3 - ok,thanks

**Comment by frapontillo** [comment]
@piernik it does, for now, but since I plan on adding new features it's best to specify what will and will not be supported. :smiley:

**Comment by piernik** [comment]
super - I'll stick to 0.4.
Maybe You should introduce 0.5 if You plan breaking changes?

**Comment by frapontillo** [comment]
If I plan any breaking changes on the switch API yes, sure.
