### ISSUE TITLE
Slow when using with ng-repeat ?

### ISSUE THREAD

**Issue by Jurigag** [frapontillo/angular-bootstrap-switch#79]
When there are many switches rendered in ng-repeat it slows down really hard a page like - 2 seconds for 30-40 switches.

**Comment by frapontillo** [comment]
Please read [**how to report issues**](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/CONTRIBUTING.md#-report-an-issue).

**Comment by Jurigag** [comment]
Live demo: http://plnkr.co/edit/NTQEx0gixo0gKIjWXWFn?p=preview
Version: 0.4.1

**Comment by frapontillo** [comment]
It's not slow in my case... Can you tell me how you think the directive can be made lighter/faster?

**Comment by frapontillo** [comment]
Closed due to inactivity.
