### ISSUE TITLE
Add commonjs package manager support

### ISSUE THREAD

**Issue by alexilyaev** [frapontillo/angular-bootstrap-switch#82]
Can we add support for loading the bsSwitch as a CommonJS module?

See example of Angular UI-Router:
https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js

This will allow doing:

``` js
var bsSwitch = require('angular-bootstrap-switch');

angular.module('admin', [
    bsSwitch,
])
```

Instead of hard coding the module name.

**Comment by frapontillo** [comment]
Sure, adding it in https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/common/module.js should be pretty straightforward.

**Comment by frapontillo** [comment]
This will not happen anymore, @alexilyaev please re-open this if you're interested in doing it, in which case I'll assign the issue to you.

**Comment by alexilyaev** [comment]
Moved to React long ago. Ditch this.
