### ISSUE TITLE
Performance issue with bigger handle-width and label-width

### ISSUE THREAD

**Issue by abullrich91** [frapontillo/angular-bootstrap-switch#86]
Hello everyone, 

First of all I'd like to say that I really like the work done with this directive and it works quite out of the box. However there is one minor nuisance that has me a bit concerned, and it involves the performance of the directive with bigger handle-width or label-width. Once these two attributes are set to something higher than let's say 20px, then the whole page starts struttering and experiencing a heavy performance hit. This can also be achieved by zooming on the page.

Here's a plnkr that shows the performance hit (try scrolling for instance of toggling the switch. You'll realize the strain).
http://plnkr.co/edit/r4qnRt

Now, here's the same code but in a smaller handle-width and label-width size. The problem is gone, however, it seems as a minor work-around the real problem.
http://plnkr.co/edit/jIdeHX

Any help on solving the performance hit would be greatly appreciated.

Thanks in advance!

All the best,

Ale Bullrich

**Comment by frapontillo** [comment]
Hmm, I really can't see any difference, the switch doesn't lag to me. Could you please tell me your configuration/machine/browser? I need to understand if it's a problem related to the AngularJS binding or to the original plugin.

Thanks!

**Comment by abullrich91** [comment]
Hi there, I'd like to report that I ran the plnkr at home (first try was at work), and the problem didn't seem to reproduce. Just to set some context, at work I have an Ubuntu machine (14.04), and ran the plnkr on Google Chrome (v. 44.0.2403.155 m). At home I have Windows 7 OS and the same Google Chrome configuration.

My home PC is far more powerful than my office machine. So for the time being, the problem seems to be localized to my work station. So first time tomorrow, I'll test the plnkr on other machines.

Thanks a lot for your assistance, and my apologies for the inconvinience.

**Comment by frapontillo** [comment]
You might want to try and make a plunker with the original bootstrap-switch to see if the problem can be attributed to the plugin.

**Comment by abullrich91** [comment]
Hi, reporting back after a night worth of sleep and back at work. I've tested the plnkr on 3 different machines (other than my own), 2 linux and 1 windows 7. On all three cases it worked flawlessly.

I downloaded Firefox at my work station and ran the plnkr once again. The memory leak didn't happen. So here is my conclusion: The directive was not responsible for the performance issue, but rather a bad combination of graphics drivers and Google Chrome managed to fudge up the page.

Once again, thanks for all the help. I'll try to download the vanilla bootstrap-switch plugin, but that will be purely for research purpose :smiley: . Please let me know if you want to add something to the discussion, but otherwise I do believe this issue is over.

**Comment by frapontillo** [comment]
Excellent, thank you for thoroughly reporting the ~~issue~~ thing. :+1:
