### ISSUE TITLE
Documentation: Explicitly include bootstrap-switch js & css when not using bower

### ISSUE THREAD

**Issue by odedfos** [frapontillo/angular-bootstrap-switch#90]
For those who don't use bower for package management it is worth mentioning in the installation notes that the angular-bootstrap-switch module depends on the bootstrap-switch module but does NOT contain it.
If embedding the files from the dist folder, you must include also the bootstrap-switch module files as well for it to work.

You may find them here:
https://github.com/nostalgiaz/bootstrap-switch/tree/v3.3.2/dist

**Comment by frapontillo** [comment]
Of course it doesn't include it, it is very clear in the docs already that "This will install AngularJS, jQuery, and the original bootstrap-switch." (see [here](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/README.md#installation)).

**Comment by shashankkrjain** [comment]
"Of course" is relative. It is not obvious for everyone and this is not clear from documentation as you say. Including one line in documentation is no harming the project, it's only helping users.

**Comment by frapontillo** [comment]
@shashankkrjain sorry it wasn't obvious to you.

It is clearly stated in `bower.json` that the main library is a dependency, and should therefore be included manually if you don't use any package manager.

If you don't understand what `bower.json` is for (and you should) then you can maybe check the `example` directory, which clearly includes the `bootstrap-switch` library separately.

**Comment by shashankkrjain** [comment]
so, you read `bower.json` of every library you are going to use?

**Comment by frapontillo** [comment]
No, since I use bower and it solves all of these issues by itself.
Do you think the documentation should also tell you to include jQuery or how to add scripts tag as well?

**Comment by shashankkrjain** [comment]
If not then you should not say "it is clearly stated in bower.json".

**Comment by frapontillo** [comment]
If you DON'T use bower you should at least try to understand how something works if you're not sure on how to use it.

Process:
1) idk how to use something
2) it's open source, so I'll browse it
3) oh, a `bower.json`, what's that for?
4) nice, I didn't know that
5) since I've learned something, let me open a pull request to update the documentation instead of complaining about it

**Comment by shashankkrjain** [comment]
I **never** said I do no use bower, btw.
