### ISSUE TITLE
How to disable indeterminate state?

### ISSUE THREAD

**Issue by easchimidt** [frapontillo/angular-bootstrap-switch#93]
Hello frapontillo,

First of all, thanks for this bootstrap switch that works with angular :)

I'm using it on a project, and I'm setting bg-switch like this:

`<input bs-switch type="checkbox"  switch-on-text="Sim" switch-off-text="Não" ng-model="acordoCheck">`

But the toggle inits in indeterminate state like the image below:

![image](https://cloud.githubusercontent.com/assets/16016802/11397589/d3a46c26-9361-11e5-8031-781b3a33c713.png)

Is there a way to init toggle in the on/off state and not in the indeterminate state?

I've tried to use bootstrap options, like data-state="false", but didn't work either.

Thanks in advance!

**Comment by easchimidt** [comment]
Ow, forget to say... I've tried to use bootstrap options, like `data-state="false"`, but didn't work either.

**Comment by easchimidt** [comment]
frapontillo,

Just figured out my problem looking at your module code.

Tried setting the ngModel 'acordoCheck' to false in my controller and it worked perfectly.

Maybe it help anybody in the future.

Thanks :)

**Comment by frapontillo** [comment]
Yes, when the model is not `true` or `false`, it will assume it means "indeterminate".

**Comment by plong0** [comment]
besides setting in controller, is there a way to disable indeterminate (ie. have it default to false)?
