### ISSUE TITLE
It is not displayed correctly in Chrome

### ISSUE THREAD

**Issue by josuesamano** [frapontillo/angular-bootstrap-switch#95]
![angswitch](https://cloud.githubusercontent.com/assets/5949714/11534956/33ac9dda-98d7-11e5-9048-67aa20745138.PNG)

IE is right
Edge is right
FireFox is right 
Only in Chrome isn't right

<code>
< input
    bs-switch
    ng-model="isSelected"
    type="checkbox"
    switch-on-text="Yes"
    switch-off-text="No"
    switch-animate="true"
    switch-label="My label is here" /></code>

**Comment by frapontillo** [comment]
There is no live demo.

**Comment by josuesamano** [comment]
I do not understand

**Comment by frapontillo** [comment]
As stated in the [contributing guide](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/CONTRIBUTING.md):
> If you have found an issue with angular-bootstrap-switch and want to report it, please make a live demo first so that the misbehaviour can be reproduced. If you don't know how to do it, simply fork and edit [this plnkr template](http://plnkr.co/edit/SWy8YmrVi8IsTa4FuqSZ).

I am not able to help you without taking a look at the issue in an isolated demo.

**Comment by frapontillo** [comment]
Closed due to inactivity.
