### ISSUE TITLE
Bootstrap Dependency 

### ISSUE THREAD

**Issue by DavidVaini** [frapontillo/angular-bootstrap-switch#98]
When installing with bower, it requires the dependency of bootstrap#4.0.0-alpha.2

The current project I am using is running bootstrap-sass-official 3.3.4

We cannot update the bootstrap version without major breaking changes.

Anyway to get this to work with that version of bootstrap?

**Comment by frapontillo** [comment]
You can specify the version of bootstrap in your own `bower.json` and it will get picked up.
